name: Deployment
on:
  push:
    branches:
      - main
    
jobs:

  build:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd projects/TProject
          git pull
          cd server
          sudo forever stopall
          npm i
          sudo forever start index.js
